import './globals.scss';

import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import React from 'react';

import BackToTop from '@/components/common/scroll-top/BackToTop';
import Footer from '@/components/frame/footer/Footer';
import { ThemeProvider } from '@/components/frame/header/color-mode/ColorProvider';
import Header from '@/components/frame/header/Header';
import { LanguageType } from '@/components/frame/header/language-mode/LanguageToggle.enum';
import { routing } from '@/i18n/routing';

import { LocalProps } from './layout.interface';

export const metadata: Metadata = {
	title: 'application',
	description: 'Generated by create next app'
};

const LocalLayout = async ({ children, params }: LocalProps) => {
	const { locale } = await params;
	// Ensure that the incoming `locale` is valid
	if (!routing.locales.includes(locale as LanguageType)) {
		notFound();
	}

	const messages = await getMessages();

	return (
		<html lang={locale} suppressHydrationWarning={true}>
			<body suppressHydrationWarning={true}>
				<NextIntlClientProvider messages={messages}>
					<ThemeProvider enableSystem defaultTheme="system" attribute="class">
						<div className="max-w-201 mx-auto px-4 sm:px-7">
							<Header />
							{children}

							<BackToTop />
						</div>
						<Footer />
					</ThemeProvider>
				</NextIntlClientProvider>
			</body>
		</html>
	);
};

export default LocalLayout;
