import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { NextIntlClientProvider, useMessages } from 'next-intl';
import React from 'react';

import BackToTop from '@/components/common/scroll-top/BackToTop';
import Footer from '@/components/frame/footer/Footer';
import { ThemeProvider } from '@/components/frame/header/color-mode/ColorProvider';
import Header from '@/components/frame/header/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'application',
	description: 'Generated by create next app'
};

interface LocalProps {
	children: React.ReactNode;
	params: {
		locale: string;
	};
}

const LocalLayout = ({ children, params: { locale } }: LocalProps) => {
	const messages = useMessages();
	return (
		<html lang={locale} suppressHydrationWarning={true}>
			<body className={inter.className} suppressHydrationWarning={true}>
				<NextIntlClientProvider locale={locale} messages={messages}>
					<ThemeProvider enableSystem defaultTheme="light" attribute="class">
						<div className="max-w-201 mx-auto px-4 sm:px-7">
							<Header />
							{children}

							<BackToTop />
						</div>
						<Footer />
					</ThemeProvider>
				</NextIntlClientProvider>
			</body>
		</html>
	);
};

export default LocalLayout;
